### ISSUE TITLE
Version 0.10.5 not available through pip

### ISSUE THREAD

**Issue by Claes1981** [kiudee/bayes-skopt#97]
**To Reproduce**
```
pip install --upgrade bask==0.10.5
ERROR: Could not find a version that satisfies the requirement bask==0.10.5
ERROR: No matching distribution found for bask==0.10.5

```
Is there perhaps a connection to there being no tag named v0.10.5 in the GitHub repo?

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by kiudee** [comment]
Thanks for the notice, the tag is pushed now.

**Comment by Claes1981** [comment]
Thanks, it works now!
