### ISSUE TITLE
Investigate the compatibility with emcee 3.1.0

### ISSUE THREAD

**Issue by kiudee** [kiudee/bayes-skopt#98]
Emcee 3.1.0 was recently released and an optimization using bask raised 
```
File "/mnt/tuning-server/venv/lib/python3.8/site-packages/emcee/backends/backend.py", line 175, in grow
a = np.empty((i, self.nwalkers, self.ndim), dtype=self.dtype)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

The library bayes-skopt currently supports all 3.x.x versions:
https://github.com/kiudee/bayes-skopt/blob/7f3e7af1d6b8f3b4f850224909d292b0d8deb387/pyproject.toml#L30
but should 3.1.0 break compatibility, steps should be taken to fix that.

**Comment by Claes1981** [comment]
This error message happened also to me with 3.1.0. I therefore downgraded from 3.1.0.

**Comment by Claes1981** [comment]
Works with Emcee 3.1.0 also for me now!
